

const productsData = [
    {
      id: '1',
      name: 'Egg Chicken Red',
      quantity: '4pcs, Price',
      price: 1.99,
      category: 'Eggs', 
      brand: 'Ifad', 
      image: require('./assets/eggsred.png'), 
      isFavorite: false,
      isCart: true,
      qty: 1,
    },
    {
      id: '2',
      name: 'Egg Chicken White',
      quantity: '180g, Price',
      price: 1.50,
      category: 'Eggs', 
      brand: 'Cocola', 
      image: require('./assets/Apple.png'),
      isFavorite: false,
    },
    {
      id: '3',
      name: 'Sprite Can',
      quantity: '325ml, Price',
      price: 1.50,
      category: 'Beverages', 
      brand: 'Cocola', 
      image: require('./assets/Sprite.png'),
      isFavorite: true, 
    },
    {
      id: '4',
      name: 'Diet Coke',
      quantity: '355ml, Price',
      price: 1.99,
      category: 'Beverages', 
      brand: 'Cocola', 
      image: require('./assets/Diet.png'),
      isFavorite: true,
    },
    {
      id: '5',
      name: 'Apple & Grape Juice',
      quantity: '2L, Price',
      price: 15.50,
      category: 'Chips & Crisps', 
      brand: 'Individual Collection', 
      image: require('./assets/Grape.png'),
      isFavorite: true, 
    },
    {
      id: '6',
      name: 'Coca Cola Can',
      quantity: '325ml, Price',
      price: 4.99,
      category: 'Beverages', 
      brand: 'Cocola', 
      image: require('./assets/Coca.png'),
      isFavorite: true,
    },
    {
      id: '7',
      name: 'Pepsi Can',
      quantity: '30gm, Price',
      price: 4.99,
      category: 'Beverages', 
      brand: 'Cocola', 
      image: require('./assets/Pepsi.png'),
      isFavorite: true, 
    },
    {
      id: '8',
      name: 'Bell Pepper Red',
      quantity: '1kg, Price',
      price: 4.99,
      category: 'Noodles & Pasta', 
      brand: 'Kazi Farmas', 
      image: require('./assets/pepperred.png'),
      isFavorite: true, 
      isCart: true,
      qty: 2, 
    },
    {
      id: '9',
      name: 'Organic Bananas',
      quantity: '1.2kg, Price', 
      price: 3.00,
      category: 'Noodles & Pasta', 
      brand: 'Kazi Farmas', 
      image: require('./assets/Banana.png'),
      isFavorite: true, 
      isCart: true,
      qty: 1,
    },
    {
      id: '10',
      name: 'Ginger',
      quantity: '250mg, Price',
      price: 2.99,
      category: 'Chips & Crisps', 
      brand: 'Individual Collection', 
      image: require('./assets/gergin.png'),
      isFavorite: true, 
      isCart: true,
      qty: 1,
    }
  ];
  
  export default productsData;